--1.-
INSERT INTO public.account (account_firstname, account_lastname, account_email, account_password)
VALUES ('Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');
--2.-
UPDATE public.account SET account_type = 'Admin' WHERE account_id = 1;
--3.-
DELETE FROM public.account WHERE account_id = 1;
--4.-
UPDATE public.inventory SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior') WHERE inv_id = 10;
--5.-
SELECT inv_make, inv_model, classification_name FROM public.inventory INNER JOIN public.classification ON public.inventory.classification_id = public.classification.classification_id WHERE classification_name = 'Sport';
--6.-
UPDATE public.inventory SET inv_image = REPLACE(inv_image, 's/', 's/vehicles/'), inv_thumbnail = REPLACE(inv_thumbnail, 's/', 's/vehicles/');

CREATE TABLE public.category (
category_id INT GENERATED BY DEFAULT AS IDENTITY,
category_name CHARACTER VARYING NOT NULL,
CONSTRAINT category_pk PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.item 
(
item_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
item_producer character varying NOT NULL,
item_name character varying NOT NULL,
item_description text NOT NULL,
item_image character varying NOT NULL,
item_price numeric(9, 2) NOT NULL,
item_details jsonb NOT NULL,
item_storage text NOT NULL,
item_amount text NOT NULL,
category_id integer NOT NULL,
CONSTRAINT item_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.enter
(
    enter_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    enter_firstname character varying NOT NULL,
    enter_lastname character varying NOT NULL,
    enter_email character varying NOT NULL,
    enter_password character varying NOT NULL,
    CONSTRAINT enter_pkey PRIMARY KEY (enter_id)
);

ALTER TABLE IF EXISTS public.item 
	ADD CONSTRAINT fk_category FOREIGN KEY (category_id)
	REFERENCES public.category (category_id) MATCH SIMPLE
	ON UPDATE CASCADE
	ON DELETE NO ACTION;


-- ignore
INSERT INTO public.category (category_name)
VALUES ('Water Soluble Fertilizers'),
	('Organic-Mineral Fertilizers'),
	('Liquid Fertilizers'),
	('Micronutrient Fertilizers');

-- Data for table `inventory`

INSERT INTO public.item (
    item_producer,
    item_name,
    item_description,
    item_image,
    item_price,
    item_details,
    item_storage,
    item_amount,
    category_id
  )
VALUES   (
    'Compo Expert',
    'Hakaphos Violeta 13-40-13',
    'Is a water soluble NPK compound fertilizer with micronutrients. High P content. Recommended formula for the rooting of the crop and for times when there are high demands of phosphorus.',
    '/products/violeta.webp',
    135.00,
    '[
      "Fast and complete water solubility",
      "Homogeneous high-quality product",
      "With chelated micronutrients added",
      "Labour-saving ready-to-use products",
      "Wide product range for optimal crop management"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 25',
    1
  ), (
    'Compo Expert',
    'Hakaphos Base 7-12-40',
    'Is a water soluble NPK compound fertilizer with sulfur and micronutrients. High K content.',
    '/products/base.webp',
    110.00,
    '[
      "Fast and complete water solubility",
      "Homogeneous high-quality product",
      "With chelated micronutrients added",
      "Labour-saving ready-to-use products",
      "Wide product range for optimal crop management"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 25',
    1
  ), (
    'Compo Expert',
    'Hakaphos Naranja 15-5-30',
    'Is a water soluble NPK compound fertilizer with magnesium, sulfur and micronutrients. High K content.',
    '/products/naranja.webp',
    140.00,
    '[
      "Fast and complete water solubility",
      "Homogeneous high-quality product",
      "With chelated micronutrients added",
      "Labour-saving ready-to-use products",
      "Wide product range for optimal crop management"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 25',
    1
  ), (
    'Compo Expert',
    'Hakaphos Rojo 18-18-18',
    'Is a water soluble NPK compound fertilizer with micronutrients. Balanced nutrient ratio. Recommended formula for flowering and balanced crop growth.',
    '/products/rojo.webp',
    120.00,
    '[
      "Fast and complete water solubility",
      "Homogeneous high-quality product",
      "With chelated micronutrients added",
      "Labour-saving ready-to-use products",
      "Wide product range for optimal crop management"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 25',
    1
  ), (
    'Compo Expert',
    'Hakaphos Azul 20-5-5',
    'Is a water soluble NPK compound fertilizer with magnesium, sulfur and micronutrients. High N content.',
    '/products/azul.webp',
    120.00,
    '[
      "Fast and complete water solubility",
      "Homogeneous high-quality product",
      "With chelated micronutrients added",
      "Labour-saving ready-to-use products",
      "Wide product range for optimal crop management"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 25',
    1
  ), (
    'Compo Expert',
    'Hakaphos Verde 15-10-15',
    'Is a water soluble NPK compound fertilizer with magnesium, sulfur and micronutrients. High NK content. Recommended formula for the beginning and maintenance of the crop in fruit trees, horticulturals, banana trees, citrus etc.',
    '/products/verde.webp',
    135.00,
    '[
      "Fast and complete water solubility",
      "Homogeneous high-quality product",
      "With chelated micronutrients added",
      "Labour-saving ready-to-use products",
      "Wide product range for optimal crop management"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 25',
    1
  ), (
    'Compo Expert',
    'Hakaphos Amarillo 17-5-19',
    'Is a water soluble NPK compound fertilizer with sulfur and micronutrients. High NK content. Nutrient salt for phosphate-reduced fertilization with almost balanced NK ratio and slight ammonium emphasis.',
    '/products/amarillo.webp',
    120.00,
    '[
      "Fast and complete water solubility",
      "Homogeneous high-quality product",
      "With chelated micronutrients added",
      "Labour-saving ready-to-use products",
      "Wide product range for optimal crop management"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 25',
    1
  ), (
    'Compo Expert',
    'Hakaphos Calcidic Plus K 14-5-24',
    'Is a water soluble NPK compound fertilizer with calcium and micronutrients. High K content. Low pH and therefore better availability of phosphate and trace elements.',
    '/products/cpk.webp',
    150.00,
    '[
      "Fast and complete water solubility",
      "Homogeneous high-quality product",
      "With chelated micronutrients added",
      "Labour-saving ready-to-use products",
      "Low pH"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 25',
    1
  ), (
    'Compo Expert',
    'Hakaphos Calcidic K-Max 10-15-28',
    'Is a water soluble NPK compound fertilizer with calcium, magnesium and micronutrients. High K content. Low pH.',
    '/products/ckm.webp',
    160.00,
    '[
      "Fast and complete water solubility",
      "Homogeneous high-quality product",
      "With chelated micronutrients added",
      "Labour-saving ready-to-use products",
      "Low pH"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 25',
    1
  ), (
    'Compo Expert',
    'Hakaphos Calcidic Plus NPK 14-6-15',
    'Is a water soluble NPK compound fertilizer with calcium and micronutrients. Low pH and therefore better availability of phosphate and trace elements.',
    '/products/cpnpk.webp',
    160.00,
    '[
      "Fast and complete water solubility",
      "Homogeneous high-quality product",
      "With chelated micronutrients added",
      "Labour-saving ready-to-use products",
      "Low pH"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 25',
    1
  ), (
    'Compo Expert',
    'Hakaphos Calcidic Plus P 10-31-10',
    'Is a water soluble NPK compound fertilizer with calcium and micronutrients. High P content. Low pH and therefore better availability of phosphate and trace elements.',
    '/products/cpp.webp',
    150.00,
    '[
      "Fast and complete water solubility",
      "Homogeneous high-quality product",
      "With chelated micronutrients added",
      "Labour-saving ready-to-use products",
      "Low pH"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 25',
    1
  ), (
    'Compo Expert',
    'Hakaphos Calcidic Plus N 19-6-6',
    'Is a water soluble NPK compound fertilizer with calcium and micronutrients. High N content. Low pH and therefore better availability of phosphate and trace elements.',
    '/products/cpn.webp',
    150.00,
    '[
      "Fast and complete water solubility",
      "Homogeneous high-quality product",
      "With chelated micronutrients added",
      "Labour-saving ready-to-use products",
      "Low pH"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 25',
    1
  ), (
    'Compo Expert',
    'TerraPlus CityGreen 6-2-5',
    'Is a pure vegan organic granular fertilizer suitable for organic farming and has been specially developed for the sustainable, biological nutrient supply of urban green spaces and versatile use in landscaping.',
    '/products/citygreen.webp',
    60.00,
    '[
      "Pure vegan fertilizer",
      "Suitable for organic farming",
      "High organic matter stability",
      "Low moisture of the granules",
      "Biostimulation and nutrient solubilization",
      "Includes Bacillus subtilis, selection E4-CDX"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, and moisture. Store loose goods inside a building and not in outdoor areas. Keep doors closed and cover heaped materials. As the product has a tendency to attract moisture, protect it from rain and standing water. Take note of the hazardous material labels on the product where appropriate. Avoid stacking more than two pallets on top of each other. Always cover loose goods and do not offload in the rain. Only transport and store at temeratures between 5 °C and 40 °C. Only store in the original packaging. Products should be used up as quickly as possible once opened.',
    'kg 20',
    2
  ), (
    'Compo Expert',
    'TerraPlus N 12-4-6(+3)',
    'Is an organic-mineral fertilizer with a high nitrogen content and supplemented by potassium alginates and humic acids.',
    '/products/tpn.webp',
    30.00,
    '[
      "High nitrogen formulation",
      "Contains humic acids and alginates to improve its effectiveness",
      "Improves the biological activity",
      "Improves the chemical-physical properties of the soil"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, and moisture. Store loose goods inside a building and not in outdoor areas. Keep doors closed and cover heaped materials. As the product has a tendency to attract moisture, protect it from rain and standing water. Take note of the hazardous material labels on the product where appropriate. Avoid stacking more than two pallets on top of each other. Always cover loose goods and do not offload in the rain.',
    'kg 25',
    2
  ), (
    'Compo Expert',
    'TerraPlus K 6-3-18(+3)',
    'Is an organic-mineral fertilizer with a high potassium content and supplemented by potassium alginates and humic acids.',
    '/products/tpk.webp',
    125.00,
    '[
      "High potassium formulation",
      "Contains humic acids and alginates to improve the effectiveness",
      "Improves the biological activity",
      "Improves the chemical-physical properties of the soil",
      "Low chloride and sodium for good compatibility"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, and moisture. Store loose goods inside a building and not in outdoor areas. Keep doors closed and cover heaped materials. As the product has a tendency to attract moisture, protect it from rain and standing water. Take note of the hazardous material labels on the product where appropriate. Avoid stacking more than two pallets on top of each other. Always cover loose goods and do not offload in the rain.',
    'kg 25',
    2
  ), (
    'Compo Expert',
    'Basfoliar Ca SL',
    'Is a pure Ca fertilizer for foliar application in Ca demanding crops, also controlling physiological leaf spots, premature leaf fall and bitter pit in apples, as well as blossom-end rot in tomatoes and other fruit and vegetable crops. It also helps to prevent physiologic leaf rot in leaf vegetables and improves the quality of vegetables and fruits.',
    '/products/csl.webp',
    149.00,
    '[
      "Prevents leaf spots and premature leaf fall in apple cultivation, prevents especially bitter pit",
      "Reduces skin and flesh browning",
      "Better storage and transport capability, improves the fruit quality, especially for sensitive crops like strawberries or cherries"
    ]'::jsonb,
    'Store inside; protect fertilizer from frost, light and high temperatures. Storage temperature: 5 °C to 30 °C. Avoid large temperature fluctuations. Do not stack the pallets. Note hazardous material labels on the product. Only store in original packaging. Use up promptly once opened.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Basfoliar CaBMg SL',
    'Is a foliar calcium fertilizer with boron and magnesium for application on crops in highly weathered or acid soils. The product also contains boron since boron nutrition is closely associated with Ca nutrition.',
    '/products/cbmsl.webp',
    180.00,
    '[
      "Prevents leaf spots and premature leaf fall in apple cultivation, prevents especially bitter pit",
      "Reduces skin and flesh browning",
      "Better storage and transport capability, improves the fruit quality, especially for sensitive crops like strawberries or cherries"
    ]'::jsonb,
    'Store inside; protect fertilizer from frost, light and high temperatures. Storage temperature: 5 °C to 30 °C. Avoid large temperature fluctuations. Do not stack the pallets. Note hazardous material labels on the product. Only store in original packaging. Use up promptly once opened.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Basfoliar CombiStipp SL',
    'Is a liquid foliar calcium-nitrogen fertilizer with boron, manganese and zinc for the control of physiological leaf spots, premature leaf fall and bitter pit in apples, as well as for combating blossom-end rot in tomatoes, other fruit and vegetable crops, physiologic leaf rot in leaf vegetables and for improving the quality of vegetables and fruits.',
    '/products/cssl.webp',
    155.00,
    '[
      "Prevents leaf spots and premature leaf fall in apple cultivation, prevents especially bitter pit",
      "Reduces skin and flesh browning",
      "Better storage and transport capability, improves the fruit quality, especially for sensitive crops like strawberries or cherries"
    ]'::jsonb,
    'Store inside; protect fertilizer from frost, light and high temperatures. Storage temperature: 5 °C to 30 °C. Avoid large temperature fluctuations. Do not stack the pallets. Note hazardous material labels on the product. Only store in original packaging. Use up quickly once opened.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Basfoliar 36 Extra SL',
    'Is a high-nitrogen foliar fertilizer with 27% N, complemented by magnesium and the complete range of essential micronutrients. The trace elements are chelated by EDTA.',
    '/products/esl.webp',
    145.00,
    '[
      "High efficiency of foliar uptake and action",
      "Compatible with most commonly used pesticides"
    ]'::jsonb,
    'Store inside; protect fertilizer from frost, light and high temperatures. Storage temperature: 5 °C to 30 °C. Avoid large temperature fluctuations. Do not stack the pallets. Note hazardous material labels on the product. Only store in original packaging. Use up promptly once opened.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Basfoliar Buffer SL',
    'Is a liquid formulation supplying the nutrients phosphorous, magnesium and zinc, and on the other hand, it is a product buffering the pH of spraying solutions towards a lower level (pH 1 in original formulation), lowering for exemple the pH of alkaline waters, or maintaining the pH of product mixtures to allow high effectivity of plant protection products and foliar fertilizers. Particularly in leafy vegetable crops and plants with developing fruit (fruit and vegetables), foliar sprays should be finely distributed to avoid runoff and drying of the accompanying agent.',
    '/products/bsl.webp',
    150.00,
    '[
      "Lowers the pH of the solution and keeps the pH stable over time",
      "Improves the efficiency of insecticides, herbicides, fungicides and growth regulators",
      "Increases the absorption rate of foliar fertilizers"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, and moisture. Store loose goods inside a building and not in outdoor areas. Keep doors closed and cover heaped materials. As the product has a tendency to attract moisture, protect it from rain and standing water. Take note of the hazardous material labels on the product where appropriate. Do not stack pallets on top of each other. Check the label or safety data sheet for the appropriate transport conditions and storage temperatures.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Basfoliar Ferro Top SL',
    'Is an iron-accentuated liquid fertilizer with nitrogen and sulfur, specifically developed for fast greening in turf and increase of vitality of the grass.',
    '/products/ftsl.webp',
    160.00,
    '[
      "Extremely fast and reliable cure of iron deficiency in turf",
      "Ideal mix for immediate formation of plant enzymes and proteins which are responsible for photosynthesis and respiration",
      "Improvement of turf resistance against moss",
      "Recommended in all high-value turf and sports fields"
    ]'::jsonb,
    'Store inside; protect fertilizer from frost, light and high temperatures. Storage temperature: 5 °C to 25 °C. Avoid large temperature fluctuations. Do not stack the pallets. Note hazardous material labels on the product. Only store in original packaging. Use up quickly once opened.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Basfoliar 10-4-7 SL',
    'Is a complete fertilizer solution with the macronutrients N, P and K as well as all essential micronutrients, with Cu, Fe, Mn and Zn completely chelated by EDTA.',
    '/products/sl.webp',
    135.00,
    '[
      "Ensures immediate absorption of nutrients, where the absorption of nutrients through the roots is difficult"
    ]'::jsonb,
    'Store inside; protect fertilizer from frost, light and high temperatures. Storage temperature: 5 °C to 30 °C. Avoid large temperature fluctuations. Do not stack the pallets. Note hazardous material labels on the product. Only store in original packaging. Use up promptly once opened.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Basfoliar Top-N SL',
    'Is a 100% water soluble clear liquid nitrogen fertilizer containing about 60% slow-release nitrogen that keeps this feature when applied foliar or via the soil. The fertilizer has been designed to provide an efficient and safe nitrogen nutrition. Basfoliar® Top-N SL has a very low salt index, giving excellent crop safety and helping to promote uniform growth and encouraging a greater root mass and more vigorous plants. Especially suitable for cereals, oilseed rape, corn, beets, potatoes, fruit and vegetable crops.',
    '/products/tnsl.webp',
    145.00,
    '[
      "60% of slow-release nitrogen",
      "Very low salt index and low EC value, does not cause leaf burn",
      "Highly resistant against leaching by rain if applied foliar",
      "Combines the rapid availability with the long-term effect of the nitrogen",
      "Highly effective nitrogen source for easy uptake by the leaves and reduced gaseous nitrogen losses"
    ]'::jsonb,
    'Store inside; protect fertilizer from frost, light and high temperatures. Storage temperature: 5 °C to 30 °C. Avoid large temperature fluctuations. Do not stack the pallets. Note hazardous material labels on the product. Only store in original packaging. Use up promptly once opened.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Basfoliar Naranja SL',
    'Is a fertilizer solution with a high content of potassium and the essential micronutrients B and Mo.',
    '/products/nsl.webp',
    180.00,
    '[
      "High efficiency of foliar uptake and action",
      "Ensures immediate absorption of nutrients, where the absorption of nutrients through the roots is difficult",
      "Compatible with most commonly used pesticides"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, and moisture. Store loose goods inside a building and not in outdoor areas. Keep doors closed and cover heaped materials. As the product has a tendency to attract moisture, protect it from rain and standing water. Take note of the hazardous material labels on the product where appropriate. Do not stack pallets on top of each other. Check the label or safety data sheet for the appropriate transport conditions and storage temperatures.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Basfoliar Ca Premium SL',
    'Contains a pH-buffered, very readily available form of calcium. The Basfoliar(r) Premium SL line is powered by the L-care technology. This special technology has been developed by COMPO EXPERT in order to achive efficient and safe application of nutrients.',
    '/products/cpsl.webp',
    160.00,
    '[
      "High uptake efficiency",
      "Leaves no spots on the fruits",
      "Promotes higher quality",
      "Safe application even at high application rate",
      "Low heavy metals content",
      "Powered by L-care technology"
    ]'::jsonb,
    'Store inside; protect fertilizer from frost, light and high temperatures. Storage temperature: 5 °C to 35 °C. Avoid large temperature fluctuations. Do not stack the pallets. Observe hazardous substance labels on the product. Only store in original packaging. Use up promptly once opened.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Basfoliar CaBMg Premium SL',
    'Contains a readily available form of calcium and magnesium. The Basfoliar® Premium SL line is powered by the L-care technology. This special technology has been developed by COMPO EXPERT in order to achieve efficient and safe application of nutrients.',
    '/products/cbmpsl.webp',
    165.00,
    '[
      "High uptake efficiency",
      "Leaves no spots on the fruits",
      "Promotes higher quality",
      "Safe application even at high application rate",
      "Low heavy metals content",
      "Powered by L-care technology"
    ]'::jsonb,
    'Store inside; protect fertilizer from frost, light and high temperatures. Storage temperature: 5 °C to 40 °C. Avoid large temperature fluctuations. Do not stack the pallets. Note hazardous material labels on the product. Only store in original packaging. Use up promptly once opened.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Basfoliar K Premium SL',
    'Is powered by the L-care technology. This special technology has been developed by COMPO EXPERT in order to achive efficient and safe application of nutrients. ',
    '/products/kpsl.webp',
    180.00,
    '[
      "Contains plant-available potassium in high concentration",
      "Leaves no spots on the fruits",
      "Promotes higher quality of the fruits",
      "Safe application even at high application rate",
      "Powered by L-care technology"
    ]'::jsonb,
    'Store inside; protect fertilizer from frost, light and high temperatures. Storage temperature: 5 °C to 35 °C. Avoid large temperature fluctuations. Do not stack the pallets. Observe hazardous substance labels on the product. Only store in original packaging. Use up promptly once opened.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Basfoliar Mg Premium SL',
    'Is ideal for supplying magnesium, an essential component of chlorophyll, and increasing pigment concentration in leaves, resulting in better SPAD values. The Basfoliar® Premium SL line is powered by Leaf Care technology. This special technology was developed by COMPO EXPERT to achieve efficient and safe nutrient application.',
    '/products/mpsl.webp',
    170.00,
    '[
      "Leaf Care technology",
      "High absorption efficiency",
      "PH buffer properties",
      "Low osmotic potential",
      "Low deliquescence point",
      "High-quality carbon sources",
      "Low heavy metal content",
      "Leaves no stains on the fruit",
      "Safe application even at high dosages"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and humidity. Avoid important temperature fluctuations. Do not stack pallets on top of each other. Observe hazard pictograms on the product. Store only in original packaging. Consume quickly after opening. Temperature range for storage: 5 °C - 40 °C.',
    'l 20',
    3
  ), (
    'Compo Expert',
    'Nutribor Fluid',
    'Is a liquid trace element fertilizer with emphasis on boron, complemented by the micronutrients manganese, molybdenum and zinc. This product was developed for foliar application, but can also be applied to the soil. It is a perfect multi-micronutrient fertilizer for the curative and the preventive treatment of trace element deficencies.',
    '/products/f.webp',
    130.00,
    '[
      "Higher yield and better quality",
      "Balanced trace element supply for healthy crops",
      "Insurance against deﬁciencies of micronutrients",
      "Crop-adapted nutrient ratio",
      "Fully chelated trace elements for optimal absorption"
    ]'::jsonb,
    'Store inside; protect fertilizer from frost, light and high temperatures. Storage temperature: 5 °C to 30 °C. Avoid large temperature fluctuations. Do not stack the pallets. Note hazardous material labels on the product. Only store in original packaging. Use up promptly once opened.',
    'l 20',
    4
  ), (
    'Compo Expert',
    'Nutribor',
    'Is a highly concentrated multi-micronutrient boron fertilizer. For boron-demanding crops (e. g., canola, maize, cotton, tobacco, oil crops, sugar beets) and boron-deficient growing conditions (sandy soils, high pH etc.). For foliar application.',
    '/products/n.webp',
    110.00,
    '[
      "Higher yield and better quality",
      "Balanced trace element supply for healthy crops",
      "Insurance against deﬁciencies of micronutrients",
      "Crop-adapted nutrient ratio"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened. Note hazardous material labels on the product.',
    'kg 15',
    4
  ), (
    'Compo Expert',
    'Nutrimix Complete',
    'Is a highly concentrated water soluble multi-micronutrient fertilizer for foliar application in cereals.',
    '/products/c.webp',
    130.00,
    '[
      "Higher yield and better quality",
      "Balanced trace element supply for healthy crops",
      "Insurance against deﬁciencies of micronutrients",
      "Crop-adapted nutrient ratio"
    ]'::jsonb,
    'Protect stored fertilizer from frost, light, high temperatures and moisture. Avoid large temperature fluctuations. Do not stack more than two pallets. Only store in original packaging. Use up quickly once opened.',
    'kg 15',
    4
  ), (
    'Compo Expert',
    'Nutrimix Fluid',
    'Is a highly concentrated liquid multi-micronutrient fertilizer with copper, manganese, molybdenum and zinc. This product was developed for foliar application, but can also be applied to the soil. It is a perfect multi-micronutrient fertilizer for the curative and the preventive treatment of trace element deficencies.',
    '/products/nf.webp',
    200.00,
    '[
      "Higher yield and better quality",
      "Balanced trace element supply for healthy crops",
      "Insurance against deﬁciencies of micronutrients",
      "Crop-adapted nutrient ratio",
      "Fully chelated trace elements for optimal absorption"
    ]'::jsonb,
    'Store inside; protect fertilizer from frost, light and high temperatures. Storage temperature: 5 °C to 30 °C. Avoid large temperature fluctuations. Do not stack the pallets. Note hazardous material labels on the product. Only store in original packaging. Use up promptly once opened.',
    'l 20',
    4
  );